build:
    wat2wasm 42.wat
    wat2wasm memory.wat
    wat2wasm minimal.wat

clean:
    rm -f *.wasm

print:
    wasm-tools print 42.wat
    wasm-tools print memory.wat
    wasm-tools print minimal.wat
